//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessiyaOneZininaMatveeva.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Activ { get; set; }
        public int Day { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public int IdModerator { get; set; }
        public int IdWinner { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
